language: android
jdk: oraclejdk7
env:
  matrix:
    - ANDROID_TARGET=android-21  ANDROID_ABI=armeabi-v7a

sudo: required

android:
  components:
    - build-tools-21.1.1
    - android-21
    - extra-android-support
    - extra-android-m2repository
    - extra-google-m2repository
